version: '3.8'

services:
  college-carpark:
    image: hiltonm420/collegecarpark:latest
    container_name: college-carpark-app
    stdin_open: true
    tty: true
    volumes:
      - ./newvrn.csv:/app/newvrn.csv
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
    restart: unless-stopped